# Site wide configuration

title:            Oscar Forner's personal website
locale:           en_GB
url:		  http://maitesin.github.io/


# Jekyll configuration

permalink:   /:title/ #/:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Oscar Forner Martinez
  avatar: avatar.jpg
  bio: "I am software developer at Programming Research. Learning Linux Kernel, passionate about GNU/Linux and OSS, enjoying algorithms and data structures and coding in C and C++11."
  email: oscar.forner.martinez@gmail.com
  disqus-shortname:
  twitter: oscar_forner
  facebook: #username
  google:
    plus: ÒscarFornerMartínez 
    analytics: UA-71699232-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: maitesin 
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: oscarforner
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
